# Generated by Django 5.2.8 on 2026-03-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutplanner', '0002_edgebanding_furniture_material_panel_stocksheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='description',
        ),
        migrations.AlterField(
            model_name='edgebanding',
            name='thickness',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
